builds:
  - ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -s -w
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarm:
      - 6
      - 7
dockers:
- image_templates:
  - "quay.io/fairwinds/kuiper:{{ .Tag }}-amd64"
  - "quay.io/fairwinds/kuiper:v{{ .Major }}-amd64"
  - "quay.io/fairwinds/kuiper:v{{ .Major }}.{{ .Minor }}-amd64"
  use_buildx: true
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/fairwinds/kuiper:{{ .Tag }}-arm64v8"
  - "quay.io/fairwinds/kuiper:v{{ .Major }}-arm64v8"
  - "quay.io/fairwinds/kuiper:v{{ .Major }}.{{ .Minor }}-arm64v8"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: quay.io/fairwinds/kuiper:{{ .Tag }}
  image_templates:
  - "quay.io/fairwinds/kuiper:{{ .Tag }}-amd64"
  - "quay.io/fairwinds/kuiper:{{ .Tag }}-arm64v8"
- name_template: quay.io/fairwinds/kuiper:v{{ .Major }}
  image_templates:
  - "quay.io/fairwinds/kuiper:v{{ .Major }}-amd64"
  - "quay.io/fairwinds/kuiper:v{{ .Major }}-arm64v8"
- name_template: quay.io/fairwinds/kuiper:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - "quay.io/fairwinds/kuiper:v{{ .Major }}.{{ .Minor }}-amd64"
  - "quay.io/fairwinds/kuiper:v{{ .Major }}.{{ .Minor }}-arm64v8"
