version: 2.1

orbs:
  rok8s-scripts: fairwinds/rok8s-scripts@11

executors:
  golang-exec:
    docker:
      - image: circleci/golang:1.15-buster

references:
  install_goreleaser: &install_goreleaser
    run:
      name: Install GoReleaser
      command: |
        curl -fsSLo goreleaser.deb https://github.com/goreleaser/goreleaser/releases/download/v0.131.1/goreleaser_amd64.deb
        echo "640790dcbfa864f26de4c26c2d491f293a64525c8c6641c5bbdec7136b38977e goreleaser.deb" | sha256sum -c -
        sudo dpkg -i goreleaser.deb
        rm goreleaser.deb
  e2e_config: &e2e_config
    command_runner_image: quay.io/reactiveops/ci-images:v11-buster
    kind_node_image: "kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca"
    executor: golang-exec
    pre_script: .circleci/pre.sh
    script: .circleci/test.sh
    filters:
      branches:
        only: /.*/
      tags:
        ignore: /.*/

jobs:
  release:
    working_directory: /go/src/github.com/fairwindsops/kuiper
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - setup_remote_docker
      - run: go mod download && go mod verify
      - *install_goreleaser
      - run:
          name: docker login
          command: docker login quay.io -u="${fairwinds_quay_user}" -p="${fairwinds_quay_token}"
      - run: goreleaser
  publish_docs:
    docker:
      - image: cimg/node:15.5.1
    steps:
      - checkout
      - run:
          name: Build Docs Site
          command: |
            set -e
            cd ./docs
            npm install
            npm run check-links
            npm run build
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Publish Docs Site to S3
          command: |
            cd ./dist
            aws s3 sync ./ s3://kuiper.docs.fairwinds.com --delete
workflows:
  version: 2
  test:
    jobs:
      - rok8s-scripts/kubernetes_e2e_tests:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          name: integration tests
          <<: *e2e_config
      - rok8s-scripts/insights:
          name: insights
  release:
    jobs:
      - release:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
