# permissions for end users to edit alternateimagesources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alternateimagesource-editor-role
rules:
- apiGroups:
  - saffire.fairwinds.com
  resources:
  - alternateimagesources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saffire.fairwinds.com
  resources:
  - alternateimagesources/status
  verbs:
  - get
