# permissions for end users to view alternateimagesources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alternateimagesource-viewer-role
rules:
- apiGroups:
  - kuiper.fairwinds.com
  resources:
  - alternateimagesources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuiper.fairwinds.com
  resources:
  - alternateimagesources/status
  verbs:
  - get
